### ISSUE TITLE
Closing channels in case of connection problems

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#100]
Is `_on_channel_close` callback should be called in case of connection lost or refused?

**Comment by mosquito** [comment]
Did you mean case of `robust_connect` mode?

**Comment by decaz** [comment]
Mostly it concerns `robust_connect` mode, and maybe it would be useful for `connect` too. I mean that `Channel._closing.done()` remains `False` while at `RobustChannel.on_reconnect` we have following: https://github.com/mosquito/aio-pika/blob/master/aio_pika/robust_channel.py#L56:L57

**Comment by decaz** [comment]
My research for this issue was started from the case of republishing messages after reconnect.
Here is the code that reproduces the bug:
```python
import asyncio
import logging

from aio_pika import Message, connect_robust

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

URL = 'amqp://guest:guest@localhost:5672/'
QUEUE_NAME = 'test'


async def on_message(message):
    logger.info('Message received: %s', message.body)


async def main():
    connection = await connect_robust(URL)
    channel = await connection.channel()
    await channel.queue_delete(QUEUE_NAME)
    queue = await channel.declare_queue(QUEUE_NAME)
    await queue.consume(on_message)

    # Here we should stop the RabbitMQ server
    logger.info('Waiting for the server shutdown. Sleeping for 10 sec...')
    await asyncio.sleep(10)
    logger.warning('The server might be offline. Wake up!')

    message = Message(b'Test')
    # `aio-pika` will try to republish the message until the server is online.
    # During that we should start the server.  When the server will be online 
    # the exception will be raised!
    await channel.default_exchange.publish(message, routing_key=QUEUE_NAME)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    try:
        loop.run_forever()
    finally:
        loop.close()
```
Here is the log:
```
decaz@pc:~/workspace/test$ python test_aio_pika.py
2018-01-26 14:59:35,465 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:35,470 - __main__ - INFO - Waiting for the server shutdown. Sleeping for 10 sec...
2018-01-26 14:59:40,116 - pika.adapters.base_connection - WARNING - Socket closed when connection was open
2018-01-26 14:59:40,116 - pika.connection - WARNING - Disconnected from RabbitMQ at localhost:5672 (320): CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'
2018-01-26 14:59:41,118 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:41,118 - pika.adapters.base_connection - WARNING - Connection to ::1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:41,119 - pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672
2018-01-26 14:59:41,119 - pika.adapters.base_connection - WARNING - Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:41,119 - pika.connection - WARNING - Could not connect, 0 attempts left
2018-01-26 14:59:42,122 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:42,123 - pika.adapters.base_connection - WARNING - Connection to ::1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:42,123 - pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672                      
2018-01-26 14:59:42,123 - pika.adapters.base_connection - WARNING - Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
...
2018-01-26 14:59:45,471 - __main__ - WARNING - The server might be offline. Wake up!
2018-01-26 14:59:46,136 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:46,136 - pika.adapters.base_connection - WARNING - Connection to ::1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:46,137 - pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672
2018-01-26 14:59:46,137 - pika.adapters.base_connection - WARNING - Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:46,137 - pika.connection - WARNING - Could not connect, 0 attempts left
2018-01-26 14:59:47,140 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:47,141 - pika.adapters.base_connection - WARNING - Connection to ::1:5672 failed: [Errno 111] Connection refused
2018-01-26 14:59:47,141 - pika.adapters.base_connection - INFO - Connecting to 127.0.0.1:5672
2018-01-26 14:59:47,141 - pika.adapters.base_connection - WARNING - Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
...
2018-01-26 14:59:51,151 - pika.adapters.base_connection - INFO - Connecting to ::1:5672
2018-01-26 14:59:51,154 - asyncio - ERROR - Future exception was never retrieved
future: <Future finished exception=ConnectionError('Auto Reconnect Error',)>
ConnectionError: Auto Reconnect Error
2018-01-26 14:59:51,478 - aio_pika.channel - ERROR - Failed to send data to client (connection unexpectedly closed)
Traceback (most recent call last):
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/channel.py", line 220, in _publish
    self._channel.basic_publish(queue_name, routing_key, body, properties, mandatory, immediate)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'
2018-01-26 14:59:51,480 - aio_pika.channel - ERROR - Channel <aio_pika.adapter.Channel object at 0x7ff6bb440160> closed: -1 - 'NoneType' object has no attribute 'send'
2018-01-26 14:59:51,481 - pika.connection - INFO - Closing connection (500): Incorrect state
2018-01-26 14:59:51,481 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<RobustConnection.connect() done, defined at /home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/robust_connection.py:99> exception=RuntimeError("Can't initialize closed channel",)>
Traceback (most recent call last):
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 105, in connect
    yield from channel.on_reconnect(self, number)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/robust_channel.py", line 64, in on_reconnect
    yield from self.initialize()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/robust_channel.py", line 74, in initialize
    result = yield from super().initialize()
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/channel.py", line 151, in initialize
    raise RuntimeError("Can't initialize closed channel")
RuntimeError: Can't initialize closed channel
Traceback (most recent call last):
  File "test_aio_pika.py", line 40, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test_aio_pika.py", line 35, in main
    await channel.default_exchange.publish(message, routing_key=QUEUE_NAME)
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/exchange.py", line 193, in publish
    immediate=immediate
  File "/home/decaz/.virtualenvs/test/lib/python3.6/site-packages/aio_pika/channel.py", line 231, in _publish
    return (yield from f)
pika.exceptions.ChannelClosed: (-1, AttributeError("'NoneType' object has no attribute 'send'",))
```

**Comment by decaz** [comment]
@mosquito do I understand correctly that this does not relates to a robust connection and it is necessary here to just correctly handle connection closing (not to continue message publishing in this case)?
https://github.com/mosquito/aio-pika/blob/53f29221033077fe98ea3b657003f060f6a5c06c/aio_pika/channel.py#L208-L210
I turned my attention to it because we cannot reuse the same channel to publish a message after reconnect (within a robust connection): `aio_pika.channel.Channel.initialize` cannot obtain `_write_lock` as it already gained by `aio_pika.channel.Channel._publish`.

**Comment by skewty** [comment]
Like you I struggled making my code robust using the callbacks provided.
You may find it easier making your own robust connection as I did at the bottom of #112.

**Comment by mosquito** [comment]
@skewty I slightly rework some part around it. Could you please reproduce your problem?

**Comment by decaz** [comment]
There are no problems with 6.3.0 version.
