### ISSUE TITLE
How to deal with ConnectionError

### ISSUE THREAD

**Issue by kerma** [mosquito/aio-pika#18]
Please document how `ConnectionError` should be handled. I have the following (simplified) setup:

```
import asyncio
import logging
from aio_pika import connect

logging.basicConfig(level=logging.DEBUG)

conn = None

async def rmq_connect():
    global conn
    loop = asyncio.get_event_loop()
    conn = await connect('amqp://guest:guest@127.0.0.1/', loop=loop)

async def close():
    global conn
    await conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(rmq_connect())

try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
finally:
    loop.run_until_complete(close())
loop.close()
```
If the RabbitMQ server goes away, the following happens:

```
ERROR:pika.adapters.base_connection:Read empty data, calling disconnect
DEBUG:pika.heartbeat:Removing timeout for next heartbeat interval
WARNING:pika.adapters.base_connection:Socket closed when connection was open
DEBUG:pika.callback:Added: {'one_shot': True, 'arguments': None, 'only': None, 'callback': <bound method Connection._on_connection_start of <aio_pika.adapter.AsyncioConnection object at 0x10497e320>>, 'calls': 1}
WARNING:pika.connection:Disconnected from RabbitMQ at 127.0.0.1:5672 (0): Not specified
DEBUG:pika.callback:Processing 0:_on_connection_closed
DEBUG:pika.callback:Calling <function Connection.connect.<locals>._on_connection_lost at 0x103d946a8> for "0:_on_connection_closed"
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError('Not specified', 0)>
ConnectionError: [Errno Not specified] 0
```

While the ERROR from pika.adapters.base_connection is ok, the one from asyncio clearly is not. I've been trying to wrap try-except blocks to every possible place without much luck. I also tried with `ensure_future` from https://docs.python.org/3/library/asyncio-dev.html#detect-exceptions-never-consumed 

I'm clearly missing something obvious here, but i couldn't find much useful after hours of looking around in code, search engines etc.

**Comment by mosquito** [comment]
Hello. Try this.

```python
import asyncio
import logging
from aio_pika import connect

logging.basicConfig(level=logging.DEBUG)

conn = None


def on_connection_closed(future):
    try:
        future.result()
    except:
        logging.exception("Oooops...")
    loop.stop()


async def rmq_connect():
    global conn
    loop = asyncio.get_event_loop()
    conn = await connect('amqp://guest:guest@127.0.0.1/', loop=loop)
    conn.add_close_callback(on_connection_closed)


async def close():
    global conn
    await conn.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(rmq_connect())

try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
finally:
    loop.run_until_complete(close())

loop.close()
```

```ERROR:root:Oooops...
Traceback (most recent call last):
  File "example.py", line 12, in on_connection_closed
    future.result()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
ConnectionError: [Errno CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'] 320```
