### ISSUE TITLE
A lot of 'MessageProcessError: Message already processed' exceptions after rejecting message

### ISSUE THREAD

**Issue by mateuszjarzyna** [mosquito/aio-pika#189]
I'm trying to reject and requeue the message. Code:

```
RABBITMQ_CONFIG = {
    'host': 'localhost',
    'queue': [
        ('hq.sample', sample_processor.processor)
    ],
    'user': 'root',
    'password': 'root123',
    'prefetch_count': os.cpu_count(),
    'connection_attempts': 5,
    'reconnect_base_delay': 4
}


async def connect(loop, initial=True):
    connection = await aio_pika.connect_robust(login=RABBITMQ_CONFIG['user'],
                                               password=RABBITMQ_CONFIG['password'],
                                               host=RABBITMQ_CONFIG['host'],
                                               retry_delay=RABBITMQ_CONFIG['reconnect_base_delay'],
                                               connection_attempts=5,
                                               loop=loop)

    channel = await connection.channel()
    await channel.set_qos(prefetch_count=RABBITMQ_CONFIG['prefetch_count'])

    queues_names = RABBITMQ_CONFIG['queue']
    for (queue, callback) in queues_names:
        queue = await channel.declare_queue(queue, durable=True)
        await queue.consume(callback)

    log.info("connected")
    return connection


async def connect_to_rabbit(loop):
    return await connect(loop)


def run_samples_consumer():
    loop = asyncio.get_event_loop()
    connection = loop.run_until_complete(connect_to_rabbit(loop))
    try:
        loop.run_forever()
    except KeyboardInterrupt as e:
        pass
    finally:
        loop.run_until_complete(connection.close())
```

And processor
```
def processor(message: aio_pika.IncomingMessage):
    with message.process():
        success = True
        if not success:
            message.reject(requeue=False)
```

And it works fine, but when I change `success` to `False` in the log file file I see few exceptions:
```
2019-01-23 13:28:59,560 [27550][MainThread][ERROR][asyncio] Exception in callback process_2g(IncomingMessa...ser_id': None}) at /.../sample_processor.py:10
handle: <Handle process_2g(IncomingMessa...ser_id': None}) at /.../sample_processor.py:10>
Traceback (most recent call last):
  File "/.../venv/lib/python3.7/site-packages/aio_pika/message.py", line 348, in process
    self.ack()
  File "/.../venv/lib/python3.7/site-packages/aio_pika/message.py", line 378, in ack
    raise MessageProcessError("Message already processed")
aio_pika.exceptions.MessageProcessError: Message already processed
```

And message is processed properly. Could you advice how to return message to queue?
I'm using aio_pika version 4.9.1

**Comment by NathanUrwin** [comment]
Hey @mateuszjarzyna 👋 

Not sure about version 4.9.1, but in the latest version (5.2.1) docs you have to specify `ignore_processed=True` if you want to manually `ack`, `nack`, or `reject` messages. See [here](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.IncomingMessage.process).
