### ISSUE TITLE
Exception when reconnecting

### ISSUE THREAD

**Issue by caiohsramos** [mosquito/aio-pika#196]
Hi,
I'm getting the following exception:
```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/caio.ramos/anaconda3/lib/python3.7/asyncio/tasks.py:592> exception=ConnectionError('0 bytes read on a total of 1 expected bytes')>
Traceback (most recent call last):
  File "/home/caio.ramos/anaconda3/lib/python3.7/site-packages/aiormq/base.py", line 22, in __await__
    return (yield from self.task.__await__(*args, **kwargs))
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caio.ramos/anaconda3/lib/python3.7/asyncio/tasks.py", line 599, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/caio.ramos/anaconda3/lib/python3.7/site-packages/aiormq/base.py", line 24, in __await__
    raise self.exception from e
ConnectionError: 0 bytes read on a total of 1 expected bytes
```
It happens after a while when I connect, and keeps repeating. I'm basically running the following code:
```
async def start_consumer():
    conn = await io_pika.connect_robust()
    queue_name = 'test_queue'

    channel = await conn.channel()

    await channel.set_qos(prefetch_count=5)

    queue = await channel.declare_queue(
        queue_name, auto_delete=True
    )

    await queue.consume(process_message)
```
The message handling works fine, but it keeps showing that exception.

**Comment by caiohsramos** [comment]
Does not seem to happen anymore in `5.2.3`. Thank you
