### ISSUE TITLE
Error "Future exception was never retrieved"

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#21]
Let's assume that the RabbitMQ server is unavailable. How such error can be suppressed? I'm already trying to catch ConnectionError..

```python
import asyncio
from aio_pika import connect

async def main(loop):
    try:
        connection = await connect('amqp://guest:guest@rabbitmq', loop=loop)
    except ConnectionError:
        print('Error!')

loop = asyncio.get_event_loop()
loop.create_task(main(loop))
loop.run_forever()
```

```
$ python rabbitmq.py 
Error!
Future exception was never retrieved
future: <Future finished exception=ConnectionRefusedError(gaierror(-3, 'Temporary failure in name resolution'),)>
Traceback (most recent call last):
  File "rabbitmq.py", line 8, in main
    connection = await connect('amqp://guest:guest@rabbitmq', loop=loop)
  File "/tmp/venv/lib/python3.6/site-packages/aio_pika/connection.py", line 209, in connect
    yield from connection.connect()
  File "/tmp/venv/lib/python3.6/site-packages/aio_pika/connection.py", line 147, in connect
    yield from f
ConnectionRefusedError: [Errno -3] Temporary failure in name resolution
```

**Comment by decaz** [comment]
I suppose, problem begins at https://github.com/mosquito/aio-pika/blob/master/aio_pika/connection.py#L131:L132 (if it is commented out, than no such error is raising).

**Comment by mosquito** [comment]
Ok. I'll try to fix this problem. But actually that's a minor problem.
