### ISSUE TITLE
In aio-pika>=5 reconnect completely broken (RobustConnection)

### ISSUE THREAD

**Issue by DriverX** [mosquito/aio-pika#231]
Try yourself.
- run one simple infinity publisher and one simple consumer in two separate process. - - restart/kill rabbitmq
- ...
- PROFIT

Reconnect logic in RobustConnection from aio-pika >= 5 is completely broken. (In aio-pika 4 broken too, but not so dramatically).

**Comment by decaz** [comment]
Duplicate of #202.

**Comment by DriverX** [comment]
I update issue with huge reproduce steps.

**Comment by DriverX** [comment]
> Duplicate of #202.

This is not duplicate

**Comment by Artimi** [comment]
I tried the reproduction code with `aiormq==2.7.2` recommended https://github.com/mosquito/aio-pika/issues/112#issuecomment-519597738 here. And it now fails with another exception.
Consumer:
```
Traceback (most recent call last):
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example/messaging_consumer.py", line 50, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "example/messaging_consumer.py", line 39, in main
    async for message in consumer:
  File "/home/artimi/wood/rabbit-messaging/rabbit_messaging/consumer.py", line 193, in __anext__
    return await self.get()
  File "/home/artimi/wood/rabbit-messaging/rabbit_messaging/consumer.py", line 128, in get
    message = await self._get()
  File "/home/artimi/wood/rabbit-messaging/rabbit_messaging/consumer.py", line 118, in _get
    message = await asyncio.shield(self._get_future)
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/channel.py", line 298, in basic_get
    await self.rpc(spec.Basic.Get(queue=queue, no_ack=no_ack))
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 171, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/artimi/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
aiormq.exceptions.ConnectionClosed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
```
Producer:
```
Traceback (most recent call last):
  File "/home/sebekpet/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example/messaging_producer.py", line 48, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/sebekpet/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/base.py", line 27, in __inner
    raise self.exception from e
  File "example/messaging_producer.py", line 35, in main
    await producer.publish('common.TestSchema.abc', data)
  File "/home/sebekpet/wood/rabbit-messaging/rabbit_messaging/producer.py", line 117, in publish
    await publish_coroutine
  File "/home/sebekpet/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aio_pika/exchange.py", line 202, in publish
    loop=self.loop, timeout=timeout
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/home/sebekpet/.virtualenvs/rabbit-messaging/lib/python3.6/site-packages/aiormq/channel.py", line 439, in basic_publish
    return await confirmation
aiormq.exceptions.ConnectionClosed: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
```
I see that you added `help wanted` tag to this @mosquito. How could I help with this?

**Comment by Artimi** [comment]
In version `aio-pika==6.1.3` I am able to achieve robust connection by catching connection exception raised from `publish` and using long-lived consumers (called with `consume` not with `get`). I tested it with RabbitMQ which is connected at the start and gets restarted during producing/consuming. This is how my wrapped publish method looks now:
```python
async def _publish(
		self,
		schema: str,
		message: aio_pika.Message,
		routing_key: str
	) -> Optional[aiormq.types.ConfirmationFrameType]:
		'''
		Publish coroutine in a special function so we can catch and ignore connection exceptions
		'''
		iterator = itertools.count() if self._retry_count is None else range(self._retry_count)
		for attempt in iterator:
			try:
				return await self._exchanges[schema].publish(message, routing_key)
			except aio_pika.exceptions.CONNECTION_EXCEPTIONS as exc:
				if attempt + 1 == self._retry_count:
					self._logger.error(
						'Message with schema = {}, routing key = {}, data = {} could not be send after = {} retries. Skipping.',
						schema,
						routing_key,
						message.body,
						self._retry_count
					)
					raise
				else:
					self._logger.warning('Connection closed while publishing with exception = {}. Will retry.', exc)
					await asyncio.sleep(self.RETRY_WAIT)
		return None
```

**Comment by mosquito** [comment]
So. Today I try to reproduce it. So, the consumer successfully connected after the rabbitmq container restart. Is it still actual?

BTW: running the rabbitmq in docker image it is a bad idea. Docker container might changing internal IP address, please use port forwarding or TCP proxy for representing this behaviour.

**Comment by monomonedula** [comment]
@mosquito yes it is

> So. Today I try to reproduce it. So, the consumer successfully connected after the rabbitmq container restart. Is it still actual?
> 
> BTW: running the rabbitmq in docker image it is a bad idea. Docker container might changing internal IP address, please use port forwarding or TCP proxy for representing this behaviour.

**Comment by svenvarkel** [comment]
Hi! 

I'm experiencing similar problem in my AWS EB environment that has RabbitMQ running in Amazon MQ.

My worker node that is connected to the queue is running well for a while but suddenly starts throwing errors and no messages move any more.

Main error message is 

```[Errno 104] Connection reset by peer``` 

Full trace looks like this:

```
Traceback (most recent call last):
File "/var/app/current/api/subsystems/queue/producer.py", line 41, in send_message
async with channel_pool.acquire() as channel:
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 142, in __aenter__
self.item = await self.pool._get()
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 104, in _get
return await self._create_item()
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 92, in _create_item
item = await self.__constructor(*self.__constructor_args)
File "/var/app/current/api/subsystems/queue/__init__.py", line 62, in _get_channel
async with connection_pool.acquire() as connection:
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 142, in __aenter__
self.item = await self.pool._get()
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 104, in _get
return await self._create_item()
File "/usr/local/lib/python3.9/site-packages/aio_pika/pool.py", line 92, in _create_item
item = await self.__constructor(*self.__constructor_args)
File "/var/app/current/api/subsystems/queue/__init__.py", line 41, in _get_connection
c: RobustConnection = await aio_pika.connect_robust(QUEUE_SERVICE_URL, loop=loop or asyncio.get_running_loop())
File "/usr/local/lib/python3.9/site-packages/aio_pika/robust_connection.py", line 271, in connect_robust
return await connect(
File "/usr/local/lib/python3.9/site-packages/aio_pika/connection.py", line 333, in connect
await connection.connect(
File "/usr/local/lib/python3.9/site-packages/aio_pika/robust_connection.py", line 127, in connect
result = await super().connect(
File "/usr/local/lib/python3.9/site-packages/aio_pika/connection.py", line 120, in connect
self.connection = await asyncio.wait_for(
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
return await fut
File "/usr/local/lib/python3.9/site-packages/aio_pika/connection.py", line 105, in _make_connection
connection = await aiormq.connect(self.url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/aiormq/connection.py", line 542, in connect
await connection.connect(client_properties or {})
File "/usr/local/lib/python3.9/site-packages/aiormq/base.py", line 168, in wrap
return await self.create_task(func(self, *args, **kwargs))
File "/usr/local/lib/python3.9/site-packages/aiormq/base.py", line 25, in __inner
return await self.task
File "/usr/local/lib/python3.9/site-packages/aiormq/connection.py", line 232, in connect
raise ConnectionError(*e.args) from e
```

I tried to reproduce this error in my local dev environment:
- I started sending messages to the queue
- in the same time I restarted RabbitMQ
- the publishing connection was restored. 
- however - consuming connection is not restored :( 
- as a result messages would be in the queue and not consumed before app is restarted.

Any ideas?

Thanks!

**Comment by mosquito** [comment]
In aio-pika>=7 reconnect completely fixed (RobustConnection) as I can see.

**Comment by gaby** [comment]
This is still happening in v9.4.0 @mosquito

Can be reproduce with https://aio-pika.readthedocs.io/en/latest/patterns.html

**Comment by mosquito** [comment]
@gaby what exactly happening?

**Comment by gaby** [comment]
> @gaby what exactly happening?

With using `connect_robust()` if the connection to `RabbitMQ`is lost (**not closed**) the logs show the consumer trying to reconnect every `5 secs`. Once `RabbitMQ` becomes reachable again, the logs stop and no new messages show up (Which I would assume means it reconnected). Instead the consumer no longer consumes from `RabbitMQ`. In the Mgmt UI, `RabbitMQ`has 0 consumer for that queue.

The log message I see during reconnect is this line (it stops when `RabbitMQ` comes back online, but consumer no longer gets messages): https://github.com/mosquito/aio-pika/blob/master/aio_pika/robust_connection.py#L83

It's the same behavior posted in https://github.com/mosquito/aio-pika/issues/231
I'm using the `aio-pika 9.4.0` with `Python 3.10`

**Comment by mosquito** [comment]
@gaby How can I reproduce the “connection lost” part?

**Comment by Darsstar** [comment]
Please try 9.4.1 (which includes #622) which removed a deadlock. The zero consumer for the queue is in like with you running into that deadlock.

**Comment by gaby** [comment]
@mosquito @Darsstar Issue still happens in v9.4.1

I can post a full example in 1-2 hrs, but basically just restarting the RabbitMQ container causes this. It's a connection lost event since it's not gracefully shutdown.

**Comment by gaby** [comment]
@mosquito @Darsstar 

worker.py
```python
import asyncio
from aio_pika import connect_robust
from aio_pika.patterns import Master, NackMessage, RejectMessage

async def worker(*, task_id: int) -> None:
    if task_id % 2 == 0:
        raise RejectMessage(requeue=False)
    if task_id % 2 == 1:
        raise NackMessage(requeue=False)
    print(task_id)

async def main() -> None:
    connection = await connect_robust(
        "amqp://guest:guest@127.0.0.1/?name=aio-pika%20worker",
    )

    # Creating channel
    channel = await connection.channel()

    # Initializing Master with channel
    master = Master(channel)
    await master.create_worker("my_task_name", worker, auto_delete=False, durable=True)

    try:
        await asyncio.Future()
    finally:
        await connection.close()

if __name__ == "__main__":
    asyncio.run(main())
```

RabbitMQ:
```bash
mkdir data
docker run -d --hostname rabbit --name rabbit -p 5672:5672 -p 15672:15672 -v $PWD/data:/var/lib/rabbitmq rabbitmq:3-management
```

Login into the UI, and click on `Queues and Streams` -> `my_task_name`, you will see `1 consumer`. Now run this:

```bash
docker kill rabbit; docker start rabbit; docker logs -f rabbit
```

You will see the logs in the worker stop printing this:
```
Connection attempt to "amqp://guest:******@127.0.0.1/?name=aio-pika%20worker" failed: Server connection reset: ConnectionResetError(104, 'Connection reset by peer'). Reconnecting after 5 seconds.
```

You will also see the following in the RabbitMQ logs:
```
2024-03-27 01:49:40.521168+00:00 [info] <0.693.0> accepting AMQP connection <0.693.0> (172.17.0.1:42788 -> 172.17.0.2:5672)
2024-03-27 01:49:40.522729+00:00 [info] <0.693.0> connection <0.693.0> (172.17.0.1:42788 -> 172.17.0.2:5672) has a client-provided name: aio-pika worker
2024-03-27 01:49:40.523354+00:00 [info] <0.693.0> connection <0.693.0> (172.17.0.1:42788 -> 172.17.0.2:5672 - aio-pika worker): user 'guest' authenticated and granted access to vhost '/'
```

But if you know click on `Queues and Streams` -> `my_task_name`, there's `0 consumers`.

Note, i'm using `auto_delete=False, durable=True`, so the Queue gets recreated again else I don't get any queue at all since the worker is not creating that queue again either.

![image](https://github.com/mosquito/aio-pika/assets/835733/1ec79f2d-2a33-482b-a57b-75ab8d946c82)

**Comment by gaby** [comment]
@mosquito @Darsstar  What I'm getting from this issues is the connection and channel are both re-created and established. The queue is not redeclared and the consumer is not re-created.

Is there a way in `aio-pika` o add a `callback` to `connect_robust()` to do those actions until a fix is in place?

**Comment by Darsstar** [comment]
There is a slight posibility that what comes next is only true in combination with #615, since repoduced your issue on that branch.

You should store the result of `master.create_worker()` since `WeakSet`s are involed. The `Worker` instance has a strong reference to the `RobustQueue` which will keep the `WeakRef` the `RobustConnection` holds alive.


With the changes in this snippet it started working.
```
    client = await master.create_worker("my_task_name", worker, auto_delete=False, durable=True)

    try:
        await asyncio.Future()
    finally:
        await client.close()
        await connection.close()
```

**Comment by gaby** [comment]
@Darsstar That fixed the issue! It now redeclares the queue and starts consuming again.

The documentation needs to be updated if the WeakRef are going to be involved.

**Comment by zvyn** [comment]
FWIW: I ran into the issue with aio-pika==9.4.3, aiormq==6.8.1 while holding strong references to the queues. My solution was to avoid `connect_robust` and simply run the complete setup again on connection loss or timeouts.
