### ISSUE TITLE
aio_pikka __init__ error due to typing

### ISSUE THREAD

**Issue by Gujjar95** [mosquito/aio-pika#242]
```Traceback (most recent call last):
  File "utility/asynio_consumer.py", line 2, in <module>
    import aio_pika
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aio_pika/__init__.py", line 1, in <module>
    from . import patterns
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aio_pika/patterns/__init__.py", line 1, in <module>
    from .master import Master, Worker, NackMessage, RejectMessage
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aio_pika/patterns/master.py", line 7, in <module>
    from aio_pika.channel import Channel
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aio_pika/channel.py", line 11, in <module>
    import aiormq
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aiormq/__init__.py", line 3, in <module>
    from . import types
  File "/Users/vikram/clickpost/venv/lib/python3.5/site-packages/aiormq/types.py", line 17, in <module>
    CallbackCoro = typing.Coroutine[DeliveredMessage, None, typing.Any]
AttributeError: module 'typing' has no attribute 'Coroutine'```

I am getting this issue during the start of the consumer.
Python Version: 3.5.2
aio-pika==6.0.1
aiohttp==2.3.10
aiormq==2.7.3

**Comment by mosquito** [comment]
Looks like your setuptools ignore [this instruction](https://github.com/mosquito/aio-pika/blob/master/setup.py#L43). Just install [typing-extensions](https://pypi.org/project/typing-extensions/) package
