### ISSUE TITLE
RuntimeError: <RobustConnection: "amqp://guest:******@192.168.99.110/" 5 channels> connection closed

### ISSUE THREAD

**Issue by heckad** [mosquito/aio-pika#305]
```
import asyncio
import gc
import weakref

import aio_pika

gc.disable()


async def f(rabbitmq_connection, weakset):
    async with rabbitmq_connection.channel() as channel:
        print('new created')

        weakset.add(channel)

    print('exetied')


async def main():
    rabbitmq_connection: aio_pika.Connection = await aio_pika.connect_robust(
        'amqp://guest:guest@localhost/'
    )

    weakset = weakref.WeakSet()

    async with rabbitmq_connection:
        for i in range(5):
            await f(rabbitmq_connection, weakset)

    await asyncio.sleep(10)
    print(len(weakset))


if __name__ == '__main__':
    asyncio.run(main())
    print('Complete')
```

**Comment by zaquest** [comment]
Seems like it's trying to reconnect, even if the connection was closed by user

```
import os
import asyncio
import logging
import aio_pika as aiopika


logger = logging.getLogger(__name__)


AMQP_BROKER = os.getenv('AMQP_BROKER')


async def test_aio_pika():
    connection = await aiopika.connect_robust(AMQP_BROKER)
    await connection.close()


def main():
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(test_aio_pika())
        loop.run_until_complete(asyncio.sleep(10))
    finally:
        loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
```

outputs

```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:aiormq.connection:Can not read bytes from server:
Traceback (most recent call last):
  File "/home/zaquest/.virtualenvs/copreso/lib/python3.6/site-packages/aiormq/connection.py", line 377, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/home/zaquest/.virtualenvs/copreso/lib/python3.6/site-packages/aiormq/connection.py", line 329, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/zaquest/.pyenv/versions/3.6.6/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
DEBUG:aio_pika.connection:Closing AMQP connection None
INFO:aio_pika.robust_connection:Connection to amqp://*** closed. Reconnecting after 5 seconds.
>>> # sleeps here, continues after 5 seconds, and finishes after 10 seconds
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<RobustConnection.reconnect() done, defined at /home/zaquest/.virtualenvs/copreso/lib/python3.6/site-packages/aio_pika/robust_connection.py:149> exception=RuntimeError('<RobustConnection: "amqp://***" 0 channels> connection closed',)>
Traceback (most recent call last):
  File "/home/zaquest/.virtualenvs/copreso/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 150, in reconnect
    await self.connect()
  File "/home/zaquest/.virtualenvs/copreso/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 105, in connect
    raise RuntimeError("{!r} connection closed".format(self))
RuntimeError: <RobustConnection: "amqp://***" 0 channels> connection closed
```

**Comment by zaquest** [comment]
This seems to solve the issue for me

```
import os
import asyncio
import logging
import aio_pika as aiopika


logger = logging.getLogger(__name__)


AMQP_BROKER = os.getenv('AMQP_BROKER')


class Connection(aiopika.RobustConnection):

    def _on_connection_close(self, connection, closing, *args, **kwargs):
        if self.reconnecting:
            return

        self.connected.clear()
        self.connection = None

        # pylint: disable=bad-super-call
        # Seems like pylint tries to warn us about infinite loop that
        # might occur, but this is not our case
        # http://pylint-messages.wikidot.com/messages:e1003
        # https://stackoverflow.com/a/18208725/1211428
        super(aiopika.RobustConnection, self) \
            ._on_connection_close(connection, closing)

        if self._closed:
            logger.info(
                'Connection to %s closed manually. Will not reconnect.',
                self
            )
        else:
            logger.info(
                'Connection to %s closed. Reconnecting after %r seconds.',
                self, self.reconnect_interval
            )
            self.loop.call_later(
                self.reconnect_interval,
                lambda: self.loop.create_task(self.reconnect())
            )


async def test_aio_pika():
    connection = await aiopika.connect_robust(
        AMQP_BROKER, connection_class=Connection
    )
    await connection.close()


def main():
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(test_aio_pika())
        loop.run_until_complete(asyncio.sleep(10))
    finally:
        loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
```

**Comment by heckad** [comment]
Еhe reason for this behaviour is in the wrong callbacks creation. For example in `robust_channel` on line 77, you add callback  with closure by `self`

```
self.add_close_callback(self._on_channel_close)
```

It adds the bound method which has reference to self. This creates a circular dependency: `self -> _done_callbacks -> bound_method<_on_channel_close> -> self`

For solve this problem need to make callback static and send senders to them explicitly.

**Comment by mosquito** [comment]
@heckad do you want to create PR for fixing it?

**Comment by heckad** [comment]
Yes, I do

**Comment by zaquest** [comment]
Am I in the wrong thread?) Is my issue related?

**Comment by zaquest** [comment]
Also that thing above, seems like it doesn't actually work and just masks the issue. Now I get other errors.

**Comment by heckad** [comment]
It's all because callbacks start working when they are no longer needed

**Comment by vashchukmaksim** [comment]
I faced the same error with RPC pattern example from the docs (and created [SO question](https://stackoverflow.com/questions/60771962/aio-pika-rpc-pattern-example-crashes-with-robustconnection-connection-closed) before finding this issue).

If it is related?

**Comment by mosquito** [comment]
@vashchukmaksim try to run [examples](https://github.com/mosquito/aio-pika/tree/master/docs/source/examples) it works fine.

**Comment by vashchukmaksim** [comment]
@mosquito Yes, I already checked it and commented on that PR. All works perfectly fine, thank you!
