### ISSUE TITLE
QueueIterator hangs forever when RabbitMQ disconnects

### ISSUE THREAD

**Issue by Phibonacci** [mosquito/aio-pika#379]
If RabbitMQ disconnect then QueueIterator will hang forever or until the coroutine is cancelled.

```python
        queue = await channel.declare_queue(queue_name, durable=True)
        try:
            async for message in queue:
                pass
```

**Comment by rob-blackbourn** [comment]
I see this too. When I set `logging.basicConfig(level=logging.DEBUG)` the following error is reported:

```bash
DEBUG:aio_pika.connection:Closing AMQP connection None
DEBUG:aiormq.connection:Reader task cancelled:
Traceback (most recent call last):
  File "/home/BHDGSYSTEMATIC.COM/rblackbourn/dev/scratch/python/aio_pika-example1/.venv/lib/python3.8/site-packages/aiormq/connection.py", line 383, in __reader
    return await self.close(
  File "/home/BHDGSYSTEMATIC.COM/rblackbourn/dev/scratch/python/aio_pika-example1/.venv/lib/python3.8/site-packages/aiormq/base.py", line 149, in close
    await self.loop.create_task(self.__closer(exc))
asyncio.exceptions.CancelledError
```

As a workaround this error can be caught by adding a `connection.add_close_callback` which *does* detect the failure:

```python
def close_callback(connection: aio_pika.Connection, error: Exception) -> None:
    if isinstance(error, ConnectionClosed):
        code, text = error.args
        if code == 320:  # "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
            print("Handle shutdown here ...")
```

**Comment by rob-blackbourn** [comment]
I have this helper method:

```python
"""Helpers for asyncio"""

import asyncio
from asyncio import Event, Future, Task
from typing import AsyncIterator, Set, TypeVar, cast

T = TypeVar('T')

async def cancel_task_and_await(task: Task) -> None:
    """Cancel a task and await it

    :param task: The task
    :type task: Task
    """
    task.cancel()
    try:
        # If the task has remaining await statements it must be awaited.
        await task
    except asyncio.CancelledError:
        pass


async def aiter_cancellable(
        async_iterator: AsyncIterator[T],
        cancellation_event: Event
) -> AsyncIterator[T]:
    """Create a cancellable async iterator.

    :param async_iterator: The async iterator to wrap
    :param cancellation_event: The asyncio Event to controll cancellation.
    :return: The wrapped async iterator
    """
    cancellation_task = asyncio.create_task(cancellation_event.wait())
    result_iter = async_iterator.__aiter__()
    pending: Set[Future] = {
        cancellation_task
    }
    while not cancellation_event.is_set():
        try:
            anext_task = asyncio.create_task(result_iter.__anext__())
            pending.add(anext_task)
            done, pending = await asyncio.wait(
                pending,
                return_when=asyncio.FIRST_COMPLETED
            )
            if anext_task in done:
                yield anext_task.result()
        except StopAsyncIteration:
            await cancel_task_and_await(cancellation_task)
            return

    for task in pending:
        await cancel_task_and_await(cast(Task, task))
```

Then this code:

```python
async def main_async():

    # Create an event that gets set when the connection fails.
    cancellation_event = asyncio.Event()

    def close_callback(_conn: aio_pika.Connection, error: Exception) -> None:
        if isinstance(error, ConnectionClosed):
            code, text = error.args
            if code == 320:  # "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
                LOGGER.error("Connection failure (%s) %s", code, text)
                cancellation_event.set()

    async with await aio_pika.connect(
            host='localhost',
            port=5672,
            virtualhost='/',
            login='guest',
            password='guest'
    ) as connection:

        connection.add_close_callback(close_callback)

        async with await connection.channel() as channel:
            queue = await channel.declare_queue('some.queue', passive=True)

            async with queue.iterator() as queue_iter:
                # Use the cancellation event HERE!!!
                async for message in aiter_cancellable(queue_iter, cancellation_event):
                    try:
                        async with message.process():
                            print(message.body.decode())
                    except:
                        print('Failed to process message')
```

**Comment by edmondburnett** [comment]
+1

**Comment by jgayfer** [comment]
Any update on this?

**Comment by mknithin** [comment]
Any update for this issue , still getting this  error in version : 8.1.1

**Comment by krasoffski** [comment]
It seems like advertised 
```
Transparent auto-reconnects with complete state recovery with connect_robust (e.g. declared queues or exchanges, consuming state and bindings).
```
does not work at all in simple queue consumer in my case.

**Comment by wallyhall** [comment]
I believe this may be related to: https://github.com/mosquito/aio-pika/issues/358 ... I've added a comment there with a work-around which solves both issues for us.

**Comment by Darsstar** [comment]
Does #615 resolve the problem? (That is the purose of the PR)

**Comment by lukaszdudek-trueenergy** [comment]
What's the status here? Is there anyone reviewing #615? Is there anything I can do to help speed this up?
We've encountered this issue in production & it's not fun to see your workers silently hang indefinitely.

**Comment by Darsstar** [comment]
> What's the status here? Is there anyone reviewing #615? Is there anything I can do to help speed this up? We've encountered this issue in production & it's not fun to see your workers silently hang indefinitely.

It got merged an hour ago 😄

**Comment by diziog** [comment]
Anyone still getting this issue?
I am using `aio_pika 9.5.5` and my workers hung forever instead of propagating a connection error.

My service logs to console (and then the logs are saved to an ES Store). I can see that at some point the application logged `Got frame for closed channel 1: <Channel.Close object at 0x7f22c5e2bec0>`. However this didn't raise any error in the code... it was just a log coming from the underlying `aiormq` library I believe. My aio_pika worker just kept working stuck at `async for message in queue.iterator():` ... obviously no messages were being processed as the connection that was used was actually shut down.

This caused my RMQ queue to have no real consumer and to have its messages stacking up. It is not the first time that this exact error happens. It makes the whole aio_pika package very unreliable and I might be forced to go on and implement a RMQ interface myself if this doesn't get fixed promptly. Production applications cannot be in a state where they silently fail and hang forever...

Is there some new fix I should try before changing package? Thank you.

**Comment by mosquito** [comment]
@diziog is this happened with with a simple non robust `Connection` class, or you use connect_robust?

The first thing I recommend doing is trying it on a regular non-robust connection, unfortunately, although the project has many tests, not all cases where the connection asynchronously falls apart are covered. The project has tests that can break the connection after a certain AMQP frame, but I don't know what exactly happened in your case.

Also a common error is when event-loop is blocked, because in the body of `async for ...` there is a blocking call, which works without a thread. I also recommend you to check this.

**Comment by mosquito** [comment]
> Why do you think that using a normal connection would have a better result?

@diziog because when connection closing you will see an exception directly without any reconnection attempts.

> After spending a bit of time investigating, it looks like that messages stopped being processed around the same time that my IT department preformed a RMQ server restart (a cluster with 3 nodes). The time of the restart coincides perfectly with when messages stopped being processed and when the RMQ consumer got deleted (I was able to check that on Grafana as we collect a lot of metrics from RMQ using Prometheus).

I'm afraid I won't get an answer to the question of what amqp frames the server sent before and after restarts
