### ISSUE TITLE
How to solve it:aiormq.exceptions.IncompatibleProtocolError: 0 bytes read on a total of 1 expected bytes

### ISSUE THREAD

**Issue by nnlaksdf** [mosquito/aio-pika#380]
The hardware used is raspberry pie 4B;

The operating system used is raspberry PI OS;

Rabbitmq uses docker rabbitmq:3-management

Set docker rabbimq -- restart = always

I want to set the following code to boot automatically, but an error was reported.The error is as follows

```
websocket server starting PORT : 0.0.0.0:8765...
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/connection.py", line 238, in connect
    res = await self.__receive_frame()
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ws_server.py", line 93, in <module>
    loop.run_until_complete(asyncio.gather(mq_env_consumer(),))
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "ws_server.py", line 12, in mq_env_consumer
    MQ_URI, loop=loop
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 284, in connect_robust
    **kwargs
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aio_pika/connection.py", line 334, in connect
    timeout=timeout, client_properties=client_properties, loop=loop,
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 128, in connect
    timeout=timeout, **self.connect_kwargs
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aio_pika/connection.py", line 121, in connect
    self._make_connection(**kwargs), timeout=timeout,
  File "/home/pi/.pyenv/versions/3.6.9/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aio_pika/connection.py", line 105, in _make_connection
    connection = await aiormq.connect(self.url, **kwargs)
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/connection.py", line 542, in connect
    await connection.connect(client_properties or {})
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/base.py", line 168, in wrap
    return await self.create_task(func(self, *args, **kwargs))
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/base.py", line 25, in __inner
    return await self.task
  File "/home/pi/.pyenv/versions/coal/lib/python3.6/site-packages/aiormq/connection.py", line 242, in connect
    raise exc.IncompatibleProtocolError(*e.args) from e
aiormq.exceptions.IncompatibleProtocolError: 0 bytes read on a total of 1 expected bytes

```

this is my code:
```
import asyncio
import websockets
import aio_pika
import json
from settings import *
from utils.log_utils import consumer_logger
from utils.json_util import dumps


async def mq_env_consumer():
    connection = await aio_pika.connect_robust(
        MQ_URI, loop=loop
    )

    queue_name = "env"
    async with connection:
        # Creating channel

        channel = await connection.channel()

        # Declaring queue
        monitor_queue = await channel.declare_queue(queue_name, auto_delete=True, durable=True)

        async with monitor_queue.iterator() as queue_iter:
            print('env consumer starting...')
            async for message in queue_iter:
                async with message.process():
                    consumer_logger.info(message.body)
                    # websocket广播
                    for i in USERS:
                        await i.send(dumps({'type': 'env',
                                            'data': json.loads(message.body.decode('utf8'))
                                            }))


async def mq_vi_consumer():
    connection = await aio_pika.connect_robust(
        MQ_URI, loop=loop
    )

    queue_name = "vi"
    async with connection:
        # Creating channel

        channel = await connection.channel()

        # Declaring queue
        monitor_queue = await channel.declare_queue(queue_name, auto_delete=True, durable=True)

        async with monitor_queue.iterator() as queue_iter:
            print('vi consumer starting...')
            async for message in queue_iter:
                async with message.process():
                    consumer_logger.info(message.body)
                    # websocket广播
                    for i in USERS:
                        await i.send(dumps({'type': 'vi',
                                            'data': json.loads(message.body.decode('utf8'))
                                            }))


USERS = set()
BLANK_LIST = set()


def register(websocket):
    USERS.add(websocket)


def unregister(websocket):
    USERS.remove(websocket)


async def websocket_handler(websocket: websockets.server.WebSocketServerProtocol, path):
    # 1.Auth Websocket client
    # 2.心跳包 20s 一个
    # 3.限制频率
    # 4.正常关闭server
    register(websocket)
    # 通过采用Cookie mac_addr的方式去登录websocket
    try:
        async for message in websocket:
            print(message)
    finally:
        unregister(websocket)


if __name__ == '__main__':
    webscoekt_server = websockets.serve(websocket_handler, "0.0.0.0", 8765)
    print('websocket server starting PORT : 0.0.0.0:8765...')
    loop = asyncio.get_event_loop()
    loop.run_until_complete(asyncio.gather(webscoekt_server, mq_env_consumer(), mq_vi_consumer()))

    asyncio.get_event_loop().run_forever()
```

**Comment by mboutet** [comment]
@nnlaksdf, did you manage to fix the problem?

**Comment by mosquito** [comment]
The reason is docker starts tcp proxy before rabbitmq binds the port. Try to use `--network=host` for the rabbitmq container

**Comment by mboutet** [comment]
Hi @mosquito, in my case, the problem arises when I close the pool during a graceful shutdown event:

```python
await asyncio.wait_for(channel_pool.close(), timeout=10)  # same problem if this line is commented
await asyncio.wait_for(connection_pool.close(), timeout=10)
```

Note that all consumers are gracefully cancelled prior to gracefully closing the connection pool.

Here are the logs in case it might help:

```python
2021-06-15 10:13:29,603 Maxences-MBP init_rabbitmq_pool[21274] DEBUG Shutting down rabbitmq pool
2021-06-15 10:13:31,606 Maxences-MBP aio_pika.robust_channel[21274] DEBUG Robust channel <RobustChannel "None#Not initialized channel"> has been closed.
2021-06-15 10:13:31,606 Maxences-MBP aio_pika.robust_channel[21274] DEBUG Robust channel <RobustChannel "None#Not initialized channel"> has been closed.
2021-06-15 10:13:33,609 Maxences-MBP aiormq.connection[21274] DEBUG Can not read bytes from server:
Traceback (most recent call last):
  File "/Users/maxenceboutet/.venvs/nuasim-di-playground/lib/python3.9/site-packages/aiormq/connection.py", line 375, in __reader
    weight, channel, frame = await self.__receive_frame()
  File "/Users/maxenceboutet/.venvs/nuasim-di-playground/lib/python3.9/site-packages/aiormq/connection.py", line 327, in __receive_frame
    frame_header = await self.reader.readexactly(1)
  File "/Users/maxenceboutet/.pyenv/versions/3.9.1/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
2021-06-15 10:13:33,612 Maxences-MBP aio_pika.connection[21274] DEBUG Closing AMQP connection None
2021-06-15 10:13:33,613 Maxences-MBP init_rabbitmq_pool[21274] DEBUG Completed shutdown of rabbitmq pool in 4009.82ms
```

**Comment by mosquito** [comment]
`asyncio.exceptions.IncompleteReadError` it's debug log, it's not a problem. That's means the connection was closed from broker side.

**Comment by mboutet** [comment]
Thanks for the explanation and thanks for this great library 👍🏼
