### ISSUE TITLE
ConnectionError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by rms-sth** [mosquito/aio-pika#438]
I have two workers: composer and its worker . The composer gets all required data and forwards to respective worker. I have about 50k data that gets processed by composer and forwards to its sub worker. During this intensive operation I am getting **"Device or resource busy"** error. Is this issue of rabbitmq or aio-pika ?

Task exception was never retrieved
future: <Task finished name='Task-89676' coro=<consumer() done, defined at /home/ramesh/Desktop/dealvault/api/venv/lib/python3.9/site-packages/aio_pika/queue.py:25> exception=ConnectionError(16, 'Device or resource busy')>
Traceback (most recent call last):
  File "/home/ramesh/Desktop/dealvault/api/venv/lib/python3.9/site-packages/aiormq/connection.py", line 228, in connect
  File "/usr/lib/python3.9/asyncio/streams.py", line 52, in open_connection
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
OSError: [Errno 16] Device or resource busy

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/queue.py", line 27, in consumer
  File "/home/ramesh/Desktop/api/servers/composer.py", line 103, in on_message
  File "/home/ramesh/Desktop/api/servers/composer.py", line 82, in dispatch_message
  File "/home/ramesh/Desktop/api/library/publisher.py", line 33, in publish
  File "/home/ramesh/Desktop/api/library/publisher.py", line 17, in init_rabbit_mq
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/robust_connection.py", line 271, in connect_robust
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/connection.py", line 333, in connect
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/robust_connection.py", line 127, in connect
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/connection.py", line 120, in connect
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aio_pika/connection.py", line 105, in _make_connection
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aiormq/connection.py", line 542, in connect
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aiormq/base.py", line 168, in wrap
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aiormq/base.py", line 25, in __inner
  File "/home/ramesh/Desktop/api/venv/lib/python3.9/site-packages/aiormq/connection.py", line 232, in connect
ConnectionError: [Errno 16] Device or resource busy

**Comment by mosquito** [comment]
Judging by the description of the problem, the operating system responded to an attempt to resolve the address with a system error. You will have to look for the reason in the network subsystem configuration in your OS.

```File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
OSError: [Errno 16] Device or resource busy```
