### ISSUE TITLE
  raise RuntimeError('Event loop is closed') 

### ISSUE THREAD

**Issue by nuri35** [mosquito/aio-pika#445]
i am getting this error how can i solve it
Consumers started
Consumer 0: Queue empty. Stopping.
Consumer 1: Queue empty. Stopping.
Consumer 2: Queue empty. Stopping.
Consumer 3: Queue empty. Stopping.
Consumer 4: Queue empty. Stopping.
Consumer 5: Queue empty. Stopping.
Consumer 7: Queue empty. Stopping.
Consumer 6: Queue empty. Stopping.
Consumer 9: Queue empty. Stopping.
Consumer 8: Queue empty. Stopping.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E41C5EEEF0>
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by mosquito** [comment]
I can't give an answer for this example. The example should be at least a runable script. If we take the code from the examples, then there are no such errors in it?

**Comment by nuri35** [comment]
can you take a look  or give example if i share it on my own github repository @mosquito  (:
