### ISSUE TITLE
Auto-reconnect not working?

### ISSUE THREAD

**Issue by QuisEgoSum** [mosquito/aio-pika#644]
The script freezes at the `channel.declare_queue` stage, namely at `await self.__restored.with()` (`robust_channel.py ` - `RobustChannel.ready`).

Python - `3.11.9`
aio-pika - `9.4.3`
RabbitMQ - `rabbitmq:4.0.2-management-alpine` or `rabbitmq:3-management-alpine`

Code:
```
import asyncio
import logging

import aio_pika

logging.basicConfig(level=logging.DEBUG)


async def main():
    connection = await aio_pika.connect_robust(
        host='127.0.0.1',
        port=5672,
        login='user',
        password='password'
    )
    async with connection:
        print(1)
        channel = connection.channel()
        print(2)
        queue = await channel.declare_queue('test', durable=True)
        print(3)
        message = aio_pika.Message('test message'.encode('utf-8'))
        print(4)
        await channel.default_exchange.publish(
            message, routing_key=queue.name
        )
        print(5)


if __name__ == '__main__':
    asyncio.run(main())

```

Logs:
```
1
2
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:aio_pika.robust_connection:Starting connection factory for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.robust_connection:Waiting for connection close event for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.robust_connection:Connection attempt for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aiormq.connection:Connecting to: amqp://user:******@127.0.0.1:5672//
DEBUG:aio_pika.robust_connection:Connection made on <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.connection:Creating AMQP channel for connection: <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.connection:Channel created: <aio_pika.robust_channel.RobustChannel object at 0x76fa5d7b2090>
DEBUG:aio_pika.robust_connection:Waiting for connection close event for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 1 channels>
DEBUG:aiormq.connection:Received frame <pamqp.heartbeat.Heartbeat object at 0x76fa5e75a450> in channel #0 weight=8 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x76fa5d7a8eb0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x08\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <pamqp.heartbeat.Heartbeat object at 0x76fa5d7b2110> in channel #0 weight=8 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x76fa5d7a8eb0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x08\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <pamqp.heartbeat.Heartbeat object at 0x76fa5e75a450> in channel #0 weight=8 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x76fa5d7a8eb0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x08\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <pamqp.heartbeat.Heartbeat object at 0x76fa5d7b25d0> in channel #0 weight=8 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x76fa5d7a8eb0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x08\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <pamqp.heartbeat.Heartbeat object at 0x76fa5e75a450> in channel #0 weight=8 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x76fa5d7a8eb0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x08\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
```

docker-compose.yaml:
```
version: '3'
services:
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine # rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
```

-----------------------------------------------

If you add while true reconnect, the script completes to the end.

Code:
```
import asyncio
import logging

import aio_pika

logging.basicConfig(level=logging.DEBUG)


async def reconnecting(connection):
    while True:
        await connection.reconnect()
        await asyncio.sleep(1)


async def main():
    connection = await aio_pika.connect_robust(
        host='127.0.0.1',
        port=5672,
        login='user',
        password='password'
    )
    async with connection:
        task = asyncio.create_task(reconnecting(connection))
        print(1)
        channel = connection.channel()
        print(2)
        queue = await channel.declare_queue('test', durable=True)
        print(3)
        message = aio_pika.Message('test message'.encode('utf-8'))
        print(4)
        await channel.default_exchange.publish(
            message, routing_key=queue.name
        )
        print(5)
        task.cancel()


if __name__ == '__main__':
    asyncio.run(main())
```

Logs:
```
1
2
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:aio_pika.robust_connection:Starting connection factory for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.robust_connection:Waiting for connection close event for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.robust_connection:Connection attempt for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aiormq.connection:Connecting to: amqp://user:******@127.0.0.1:5672//
DEBUG:aio_pika.robust_connection:Connection made on <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.connection:Creating AMQP channel for connection: <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 0 channels>
DEBUG:aio_pika.connection:Channel created: <aio_pika.robust_channel.RobustChannel object at 0x7005796b5250>
DEBUG:aiormq.connection:Closing connection <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969bbb0> cause: <class 'asyncio.exceptions.CancelledError'>
DEBUG:aiormq.connection:Sending <Connection.Close object at 0x70057968af90> to <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969bbb0>
DEBUG:aiormq.connection:Reader exited for <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969bbb0>
DEBUG:aiormq.connection:Writer on connection amqp://user:******@127.0.0.1:5672// closed
DEBUG:aiormq.connection:Writer exited for <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969bbb0>
DEBUG:aiormq.connection:Closing connection <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969bbb0> cause: CancelledError()
INFO:aio_pika.robust_connection:Connection to amqp://user:******@127.0.0.1:5672// closed. Reconnecting after 5 seconds.
DEBUG:aio_pika.robust_connection:Waiting for connection close event for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 1 channels>
DEBUG:aio_pika.robust_connection:Connection attempt for <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 1 channels>
DEBUG:aiormq.connection:Connecting to: amqp://user:******@127.0.0.1:5672//
DEBUG:aio_pika.channel:Start reopening channel <aio_pika.robust_channel.RobustChannel object at 0x7005796b5250>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x01\x00\x01\x00\x00\x00\x06\x00\x14\x00\n\x010\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <Channel.OpenOk object at 0x7005796b6750> in channel #1 weight=16 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x01\x00\x01\x00\x00\x00\x05\x00U\x00\n\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <Confirm.SelectOk object at 0x7005796b7150> in channel #1 weight=12 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x01\x00\x01\x00\x00\x00\x0b\x00<\x00\n\x00\x00\x00\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <Basic.QosOk object at 0x7005796b74d0> in channel #1 weight=12 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aio_pika.queue:Declaring queue: <RobustQueue(test): auto_delete=False, durable=True, exclusive=False, arguments=None
DEBUG:aio_pika.robust_connection:Connection made on <RobustConnection: "amqp://user:******@127.0.0.1:5672//" 1 channels>
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x01\x00\x01\x00\x00\x00\x10\x002\x00\n\x00\x00\x04test\x02\x00\x00\x00\x00\xce', should_close=False, drain_future=None)
DEBUG:aiormq.connection:Received frame <Queue.DeclareOk object at 0x7005796bae40> in channel #1 weight=25 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aio_pika.exchange:Publishing message with routing key 'test' via exchange <RobustExchange(): auto_delete=False, durable=False, arguments={})>: Message:{'app_id': None,
 'body_size': 12,
 'cluster_id': None,
 'consumer_tag': None,
 'content_encoding': None,
 'content_type': None,
 'correlation_id': None,
 'delivery_mode': <DeliveryMode.NOT_PERSISTENT: 1>,
 'delivery_tag': None,
 'exchange': None,
 'expiration': None,
 'headers': {},
 'message_id': None,
 'priority': 0,
 'redelivered': None,
 'reply_to': None,
 'routing_key': None,
 'timestamp': None,
 'type': 'None',
 'user_id': None}
DEBUG:aiormq.connection:Prepare to send ChannelFrame(payload=b'\x01\x00\x01\x00\x00\x00\r\x00<\x00(\x00\x00\x00\x04test\x01\xce\x02\x00\x01\x00\x00\x005\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c8\x80\x00\x00\x00\x00\x01\x00 6bbd05858eef4baf9a4612102131e8c6\xce\x03\x00\x01\x00\x00\x00\x0ctest message\xce', should_close=False, drain_future=<Future pending cb=[FutureStore.__on_task_done.<locals>.remover() at /home/quisegosum/Project/test-aio-pika/.venv/lib/python3.11/site-packages/aiormq/base.py:33, <1 more>, Task.task_wakeup()]>)
DEBUG:aiormq.connection:Received frame <Basic.Ack object at 0x7005796bb890> in channel #1 weight=21 on <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Sending <Connection.Close object at 0x70057968b470> to <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Reader exited for <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Writer on connection amqp://user:******@127.0.0.1:5672// closed
DEBUG:aiormq.connection:Writer exited for <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0>
DEBUG:aiormq.connection:Closing connection <Connection: "amqp://user:******@127.0.0.1:5672//" at 0x70057969b3e0> cause: CancelledError()
Exception ignored in: <coroutine object OneShotCallback.__task_inner at 0x7005796c06d0>
Traceback (most recent call last):
  File "/home/quisegosum/Project/test-aio-pika/.venv/lib/python3.11/site-packages/aio_pika/tools.py", line 244, in __task_inner
    self.loop.call_soon(self.finished.set)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-42' coro=<OneShotCallback.__task_inner() done, defined at /home/quisegosum/Project/test-aio-pika/.venv/lib/python3.11/site-packages/aio_pika/tools.py:236>>
3
4
5
```

**Comment by QuisEgoSum** [comment]
Solution
```
channel = await connection.channel()
```
