### ISSUE TITLE
Event loop is closed when exiting QueueIterator

### ISSUE THREAD

**Issue by bitrut** [mosquito/aio-pika#71]
I've been trying to use QueueIterator. I run the example from the home page of docs for simple producer and consumer. I'm getting this error:
```
Exception ignored in: <bound method QueueIterator.__del__ of <aio_pika.queue.QueueIterator object at 0x10d7da6a0>>
Traceback (most recent call last):
  File "/Users/bitrut/.virtualenvs/conradlib/lib/python3.6/site-packages/aio_pika/queue.py", line 362, in __del__
    self.close()
  File "/Users/bitrut/.virtualenvs/conradlib/lib/python3.6/site-packages/aio_pika/queue.py", line 359, in close
    return self.loop.create_task(self._close())
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 282, in create_task
    self._check_closed()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I can't figure out what's wrong.

**Comment by mosquito** [comment]
Can you add some example which reproduces this?

**Comment by bitrut** [comment]
@mosquito Sure.
https://gist.github.com/bitrut/bc22224cd19bb06d404f8cf7059b5f6d

**Comment by mosquito** [comment]
@bitrut it's looks like you close the event loop but the event-loop has uncompleted tasks. 
Try to wait it before:

```python
await asyncio.wait(t for t in asyncio.Task.all_tasks() if not t.done())
```

**Comment by bitrut** [comment]
I updated my gist, but problem stays the same.
I guess the `await` before `asyncio.wait` was not needed. It doesn't return coroutine.

**Comment by mosquito** [comment]
@bitrut it's wrong. `asyncio.wait` returns awaitable object. You have to wrap to your function like this:

```python

async def main():
    # do something
    pass


async def entrypoint(loop):
    try:
        await main()
    finally:
        await asyncio.wait(t for t in asyncio.Task.all_tasks() if not t.done(), loop=loop)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(entrypoint(loop))
    finally:
        loop.close()
```

**Comment by bitrut** [comment]
Updated gist again.
Consumer code blocks after breaking from `for` loop. It seems that it waits forever for a pending task. But I don't know how to find out what task it is.

**Comment by mosquito** [comment]
It might be avoided when you close connection properly.

In `aio-pika>=1.5` you should be use:

```python
async with connection:
    ....
```
