### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by pquentin** [mosquito/aio-pika#8]
I'm refering to the [sample code in the project's README](https://raw.githubusercontent.com/mosquito/aio-pika/c9409a869149cd1dd9bdc49f4a991aa40c2b4ddf/README.rst).

First, I had to change acyncio in asyncio. Next I had to also import Message from aio_pika. But even then, I get this error:

```
Traceback (most recent call last):
  File "t.py", line 47, in <module>
    loop.run_until_complete(main(loop))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "t.py", line 35, in main
    incoming_message = yield from queue.get(timeout=5)
  File "venv/lib/python3.6/site-packages/aio_pika/queue.py", line 145, in get
    no_ack=no_ack,
  File "venv/lib/python3.6/site-packages/aio_pika/message.py", line 150, in __init__
    self.consumer_tag = envelope.consumer_tag
AttributeError: 'GetOk' object has no attribute 'consumer_tag'
```

What is going on?

Thanks for aio-pika!

**Comment by mosquito** [comment]
Hmmm. I try to reproduce it on 3.6.1

**Comment by mosquito** [comment]
Please add information about your environment (broker version, python version, etc.)

**Comment by mosquito** [comment]
Ha-ha. Now I see typo. Thank you. Fixed.

**Comment by mosquito** [comment]
Fixed. Try to use 0.6.4.

**Comment by pquentin** [comment]
Thanks, this fixed it. Sorry for the lack of details.
